# Netherlands Neurogenetics Database
Author: Nienke Mekkes <br>
Date: 21-Sep-2022. <br>
Correspond: n.j.mekkes@umcg.nl <br>

## Script: clinical history labeled training data: splitting data
Objectives: load cleaned training data, split into <br>
- test (will be stored separately)
- train&val (serves as input for our models)

Ideally, the distribution of attributes is similar between the test set and the train/val set. Therefore we stratify the data using the attributes. In other words, our testset will not contain attributes not present in the train&valset, and vice versa. <br>
We assume that we do not have to stratify the donors (e.g. on sex, or diagnosis), since our task is predicting attribute labels

### Input files:
- excel file with cleaned labeled training data, OR
- pickle file with cleaned labeled training data

### Output
- Folder containing:
    - trainval data (excel and pickle)
    - test data (excel and pickle)




#### Minimal requirements

In [8]:
# %pip install pandas
# %pip install openpyxl
# %pip install iterative-stratification
# %pip install scikit-multilearn
# %pip install natsort ?
# %pip install nltk

#### Imports

In [1]:
import pickle
import pandas as pd
import numpy as np
import os
from iterstrat.ml_stratifiers import MultilabelStratifiedKFold
from datetime import date
from helper_functions import split_vis

#### Paths (user input required)

In [2]:
#path_to_cleaned_training_data_xlsx = '/data/p307948/clinical/github_data/output/cleaned_training_data.xlsx'
path_to_cleaned_training_data_pkl = "/home/jupyter-n.mekkes@gmail.com-f6d87/ext_n_mekkes_gmail_com/clinical_history/training_data/cleaned_training_data.pkl"
save_path_files = '/home/jupyter-n.mekkes@gmail.com-f6d87/ext_n_mekkes_gmail_com/clinical_history/training_data'

In [3]:
if not os.path.exists(save_path_files):
    print('Creating output folder....')
    os.makedirs(save_path_files)

#### Loading data


In [5]:
# cleaned_train = pd.read_excel(path_to_cleaned_training_data_xlsx), engine='openpyxl', index_col=[0])
with open(path_to_cleaned_training_data_pkl, "rb") as file:
    cleaned_train = pickle.load(file)
display(cleaned_train)

NBB_nr  Year_Sentence_nr  \
0      NBB 1990-048   Past_sentence_0   
1      NBB 1990-048   Past_sentence_1   
2      NBB 1990-048   1979_sentence_0   
3      NBB 1990-048   1979_sentence_1   
4      NBB 1990-048   1979_sentence_2   
...             ...               ...   
19049  NBB 2018-114  2018_sentence_25   
19050  NBB 2018-114  2018_sentence_26   
19051  NBB 2018-114  2018_sentence_27   
19052  NBB 2018-114  2018_sentence_28   
19053  NBB 2018-114  2018_sentence_29   

                                                Sentence  Muscular_Weakness  \
0      Past: The patient was known to have atrial fib...                  0   
1      The patient was known to have hypertension and...                  0   
2                              1979: She got a total hip                  0   
3       At age 76 the first demential symptomes appeared                  0   
4      After the death of her husband homesituation w...                  0   
...                                                  ...                ...   
19049  The patient himself did not recognize himself ...                  0   
19050  In July and August he suffered from deliria po...                  0   
19051  In August the GP reported that it was impossib...                  0   
19052  This was a reason why a hospice turned down an...                  0   
19053  In September the patient was euthanized and de...                  0   

       Spasticity  Hyperreflexia_and_oth_reflexes  Frontal_release_signs  \
0               0                               0                      0   
1               0                               0                      0   
2               0                               0                      0   
3               0                               0                      0   
4               0                               0                      0   
...           ...                             ...                    ...   
19049           0                               0                      0   
19050           0                               0                      0   
19051           0                               0                      0   
19052           0                               0                      0   
19053           0                               0                      0   

       Fasciculations  Positive_sensory_symptoms  Negative_sensory_symptoms  \
0                   0                          0                          0   
1                   0                          0                          0   
2                   0                          0                          0   
3                   0                          0                          0   
4                   0                          0                          0   
...               ...                        ...                        ...   
19049               0                          0                          0   
19050               0                          0                          0   
19051               0                          0                          0   
19052               0                          0                          0   
19053               0                          0                          0   

       ...  Orthostatic_hypotension  Headache_migraine  Fatigue  \
0      ...                        0                  0        0   
1      ...                        0                  0        0   
2      ...                        0                  0        0   
3      ...                        0                  0        0   
4      ...                        0                  0        0   
...    ...                      ...                ...      ...   
19049  ...                        0                  0        0   
19050  ...                        0                  0        0   
19051  ...                        0                  0        0   
19052  ...                        0    

#### Data preparation

In [6]:
non_attribute_columns = ['NBB_nr','Year_Sentence_nr','Sentence']
attributes = [col for col in cleaned_train.columns if col not in non_attribute_columns]
print(len(attributes))

90


#### Split set-up (user input required)

- 'X' contains the sentences
- 'Y' contains the attribute labels (numpy array of 1s and 0s per sentence)

In [7]:
train_val_size = 0.8
test_size = 0.2
print(cleaned_train[['Sentence']])
X = cleaned_train[['Sentence']].to_numpy()
Y = cleaned_train.loc[:,[i for i in list(cleaned_train.columns) if i not in non_attribute_columns]].to_numpy()

                                                Sentence
0      Past: The patient was known to have atrial fib...
1      The patient was known to have hypertension and...
2                              1979: She got a total hip
3       At age 76 the first demential symptomes appeared
4      After the death of her husband homesituation w...
...                                                  ...
19049  The patient himself did not recognize himself ...
19050  In July and August he suffered from deliria po...
19051  In August the GP reported that it was impossib...
19052  This was a reason why a hospice turned down an...
19053  In September the patient was euthanized and de...

[18917 rows x 1 columns]


In [8]:
print(X)
print(Y)

[['Past: The patient was known to have atrial fibrillation']
 ['The patient was known to have hypertension and a struma during WWII']
 ['1979: She got a total hip']
 ...
 ['In August the GP reported that it was impossible to get him to sleep despite consulting geriatric specialists and trying several medications sleeping was of major concern']
 ['This was a reason why a hospice turned down an admission']
 ['In September the patient was euthanized and deceased at home']]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### Iterative split, approach MultilabelStratifiedKFold (preferred)
MultilabelStratifiedKFold is very suitable for creating multiple stratified folds for datasets with multiple labels. This is why we use it when training and optimizing the model later, when using the train&val dataset. Here we create the train&val dataset, and although we do not use multiple folds (we think one test set is enough), we do use the same library for continuity and ease of use. <br>

We will never reach 'perfect' stratification, since a sentence can only be present in either test, or train&val, and some sentences contain multiple attributes

MultilabelStratifiedKFold takes n_splits as input, and creates n_splits folds. <br>
1/n_splits part of the data will be used as test, and the remainder for train. <br>
e.g. for an n_splits of 5 and 10 sentences, 2 sentences function as test (==1/5), and 8 sentences as train. <br>
This is performed 5 times, leading to 5 different 2-8 combinations. <br>

Importantly, we only need a single 2-8 combination, so we exit the loop after a single run!

In [9]:
mskf = MultilabelStratifiedKFold(n_splits=5, shuffle=True, random_state=1)
j = 0
for train_val_index, test_index in mskf.split(X, Y):
    if j == 0:
        print("TRAINVAL row numbers:", train_val_index, "\nTEST row numbers:", test_index)
        x_train_val, x_test = X[train_val_index], X[test_index]
        y_train_val, y_test = Y[train_val_index], Y[test_index]
        print(f"nr of sentences in train&val: {len(x_train_val)}, or {len(x_train_val)/(len(x_train_val)+len(x_test)):.2f}%\n"\
        f"nr of sentences in test: {len(x_test)}, or {len(x_test)/(len(x_train_val)+len(x_test)):.2f}%")
        print('\nFinished splitting data once, exiting loop...')
        break

TRAINVAL row numbers: [    0     2     3 ... 18913 18915 18916] 
TEST row numbers: [    1     4     8 ... 18897 18904 18914]
nr of sentences in train&val: 15133, or 0.80%
nr of sentences in test: 3784, or 0.20%

Finished splitting data once, exiting loop...


#### Investigate if attributes are distributed roughly equally between test and train&val

In [10]:
pd.options.display.max_columns = 100
std,uncor, cor = split_vis(x_train_val,x_test,y_train_val, y_test,x_train_val.shape[0],x_test.shape[0],attributes)
print('Stratification score: ', round(std,4))

print('Attribute distribution real numbers:')
display(uncor)

print('Attribute distribution numbers adjusted for sizes of train&val and test:')
display(cor)

Stratification score:  0.9167
Attribute distribution real numbers:


Muscular_Weakness  Spasticity  Hyperreflexia_and_oth_reflexes  \
train_and_val                294         113                             118   
test                          73          28                              30   

               Frontal_release_signs  Fasciculations  \
train_and_val                     21               6   
test                               6               1   

               Positive_sensory_symptoms  Negative_sensory_symptoms  \
train_and_val                        115                         66   
test                                  29                         16   

               Parkinsonism  Facial_masking  Tremor  Bradykinesia  Rigidity  \
train_and_val           127              68     147           205       157   
test                     32              18      37            51        40   

               Vertigo  Nystagmus  Ataxia  Loss_of_coordination  \
train_and_val       28         33      72                    82   
test                 7          8      18                    20   

               Balance_problems  Frequent_falls  Decreased_motor_skills  \
train_and_val               128             101                      74   
test                         32              25                      19   

               Unspecified_disturbed_gait_patt  Mobility_problems  Dementia  \
train_and_val                               15                426       293   
test                                         3                106        74   

               Cognitive_decline  Bradyphrenia  Lack_of_insight  \
train_and_val                236            64               92   
test                          59            16               22   

               Facade_behavior  Head_turning_sign  Memory_impairment  Amnesia  \
train_and_val               20                  6                371       41   
test                         5                  2                 93       10   

               Forgetfulness  Imprinting_disturbances  Impaired_recognition  \
train_and_val            114                       64                    49   
test                      28                       17                    12   

               Confabulations  Disorientation  Wandering  Confusion  Aphasia  \
train_and_val              24             237         40        127       49   
test                        6              59         10         32       13   

               Word_finding_problems  Language_impairment  \
train_and_val                    110                  211   
test                              27                   53   

               Impaired_comprehension  Communication_problems  Dysarthria  \
train_and_val                      93                      54          91   
test                               23                      14          23   

               Apraxia  Executive_function_disorder  \
train_and_val       96                           33   
test                24                            8   

               Lack_of_planning_organis_overv  Concentration_problems  \
train_and_val                              56                     127   
test                                       15                      31   

               Disinhibition  Loss_of_decorum  Apathy_inertia  \
train_and_val             66              118              45   
test                      17               29              11   

               Lack_of_initiative  Loss_of_sympathy_empathy  \
train_and_val                  49                         7   
test                           12                         2   

               Compulsive_behavior  Hyperorality  Changed_moods_emotions  \
train_and_val                   95            30                     136   
test                            24             7                      34   

               Changed_behavior_personality  Agitation  Aggressive_behavior  \
train_and_val                           235        106            

Attribute distribution numbers adjusted for sizes of train&val and test:


Muscular_Weakness  Spasticity  Hyperreflexia_and_oth_reflexes  \
train_and_val                294         113                             118   
test                         291         111                             119   

               Frontal_release_signs  Fasciculations  \
train_and_val                     21               6   
test                              23               3   

               Positive_sensory_symptoms  Negative_sensory_symptoms  \
train_and_val                        115                         66   
test                                 115                         63   

               Parkinsonism  Facial_masking  Tremor  Bradykinesia  Rigidity  \
train_and_val           127              68     147           205       157   
test                    127              71     147           203       159   

               Vertigo  Nystagmus  Ataxia  Loss_of_coordination  \
train_and_val       28         33      72                    82   
test                27         31      71                    79   

               Balance_problems  Frequent_falls  Decreased_motor_skills  \
train_and_val               128             101                      74   
test                        127              99                      75   

               Unspecified_disturbed_gait_patt  Mobility_problems  Dementia  \
train_and_val                               15                426       293   
test                                        11                423       295   

               Cognitive_decline  Bradyphrenia  Lack_of_insight  \
train_and_val                236            64               92   
test                         235            63               87   

               Facade_behavior  Head_turning_sign  Memory_impairment  Amnesia  \
train_and_val               20                  6                371       41   
test                        19                  7                371       39   

               Forgetfulness  Imprinting_disturbances  Impaired_recognition  \
train_and_val            114                       64                    49   
test                     111                       67                    47   

               Confabulations  Disorientation  Wandering  Confusion  Aphasia  \
train_and_val              24             237         40        127       49   
test                       23             235         39        127       51   

               Word_finding_problems  Language_impairment  \
train_and_val                    110                  211   
test                             107                  211   

               Impaired_comprehension  Communication_problems  Dysarthria  \
train_and_val                      93                      54          91   
test                               91                      55          91   

               Apraxia  Executive_function_disorder  \
train_and_val       96                           33   
test                95                           31   

               Lack_of_planning_organis_overv  Concentration_problems  \
train_and_val                              56                     127   
test                                       59                     123   

               Disinhibition  Loss_of_decorum  Apathy_inertia  \
train_and_val             66              118              45   
test                      67              115              43   

               Lack_of_initiative  Loss_of_sympathy_empathy  \
train_and_val                  49                         7   
test                           47                         7   

               Compulsive_behavior  Hyperorality  Changed_moods_emotions  \
train_and_val                   95            30                     136   
test                            95            27                     135   

               Changed_behavior_personality  Agitation  Aggressive_behavior  \
train_and_val                           235        106            

#### Creating final dataframes

In [11]:
trainval_df = pd.DataFrame(x_train_val,columns=['text'])
trainval_df['labels'] = y_train_val.tolist()
trainval_df.to_excel(f"{save_path_files}/trainval_data.xlsx")
trainval_df.to_pickle(f"{save_path_files}/trainval_data.pkl") 


test_df = pd.DataFrame(x_test,columns=['text'])
test_df['labels'] = y_test.tolist()
test_df.to_excel(f"{save_path_files}/test_data.xlsx")
test_df.to_pickle(f"{save_path_files}/test_data.pkl") 